name: GrayjayiOS
options:
  bundleIdPrefix: com.futo
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 6.20.0
targets:
  GrayjayiOS:
    type: application
    platform: iOS
    deploymentTarget: "14.4"
    sources:
      - path: GrayjayiOS/App
      - path: GrayjayiOS/Core
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIBackgroundModes:
          - audio
    dependencies: 
      - package: GRDB
